apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development

spec:
  selector:
    app.kubernetes.io/name: jekyll
  type: NodePort
  ports:
    - port: 8080
      targetPort: 4000
      nodePort: 30097
  